//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.1432.
// 
namespace D2L.WS.Client.Proxy {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AuthenticationTokenServiceSoap", Namespace="http://desire2learn.com/security/token/2007/08")]
    public partial class AuthenticationTokenService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AuthenticateOperationCompleted;
        
        private System.Threading.SendOrPostCallback Authenticate2OperationCompleted;
        
        private System.Threading.SendOrPostCallback AuthenticateWithAppTokenOperationCompleted;
        
        /// <remarks/>
        public AuthenticationTokenService() {
            this.Url = "http://localhost/d2l/AuthenticationTokenService.asmx";
        }
        
        /// <remarks/>
        public event AuthenticateCompletedEventHandler AuthenticateCompleted;
        
        /// <remarks/>
        public event Authenticate2CompletedEventHandler Authenticate2Completed;
        
        /// <remarks/>
        public event AuthenticateWithAppTokenCompletedEventHandler AuthenticateWithAppTokenCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://desire2learn.com/security/token/2007/08/Authenticate", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("AuthenticateResponse", Namespace="http://desire2learn.com/security/token/2007/08")]
        public AuthenticateResponse Authenticate([System.Xml.Serialization.XmlElementAttribute(Namespace="http://desire2learn.com/security/token/2007/08")] AuthenticateRequest AuthenticateRequest) {
            object[] results = this.Invoke("Authenticate", new object[] {
                        AuthenticateRequest});
            return ((AuthenticateResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAuthenticate(AuthenticateRequest AuthenticateRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Authenticate", new object[] {
                        AuthenticateRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public AuthenticateResponse EndAuthenticate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((AuthenticateResponse)(results[0]));
        }
        
        /// <remarks/>
        public void AuthenticateAsync(AuthenticateRequest AuthenticateRequest) {
            this.AuthenticateAsync(AuthenticateRequest, null);
        }
        
        /// <remarks/>
        public void AuthenticateAsync(AuthenticateRequest AuthenticateRequest, object userState) {
            if ((this.AuthenticateOperationCompleted == null)) {
                this.AuthenticateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenticateOperationCompleted);
            }
            this.InvokeAsync("Authenticate", new object[] {
                        AuthenticateRequest}, this.AuthenticateOperationCompleted, userState);
        }
        
        private void OnAuthenticateOperationCompleted(object arg) {
            if ((this.AuthenticateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthenticateCompleted(this, new AuthenticateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://desire2learn.com/security/token/2007/08/Authenticate2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("AuthenticateResponse", Namespace="http://desire2learn.com/security/token/2007/08")]
        public AuthenticateResponse Authenticate2([System.Xml.Serialization.XmlElementAttribute(Namespace="http://desire2learn.com/security/token/2007/08")] AuthenticateRequest2 AuthenticateRequest2) {
            object[] results = this.Invoke("Authenticate2", new object[] {
                        AuthenticateRequest2});
            return ((AuthenticateResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAuthenticate2(AuthenticateRequest2 AuthenticateRequest2, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Authenticate2", new object[] {
                        AuthenticateRequest2}, callback, asyncState);
        }
        
        /// <remarks/>
        public AuthenticateResponse EndAuthenticate2(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((AuthenticateResponse)(results[0]));
        }
        
        /// <remarks/>
        public void Authenticate2Async(AuthenticateRequest2 AuthenticateRequest2) {
            this.Authenticate2Async(AuthenticateRequest2, null);
        }
        
        /// <remarks/>
        public void Authenticate2Async(AuthenticateRequest2 AuthenticateRequest2, object userState) {
            if ((this.Authenticate2OperationCompleted == null)) {
                this.Authenticate2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenticate2OperationCompleted);
            }
            this.InvokeAsync("Authenticate2", new object[] {
                        AuthenticateRequest2}, this.Authenticate2OperationCompleted, userState);
        }
        
        private void OnAuthenticate2OperationCompleted(object arg) {
            if ((this.Authenticate2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Authenticate2Completed(this, new Authenticate2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://desire2learn.com/security/token/2007/08/AuthenticateWithAppToken", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("AuthenticateResponse", Namespace="http://desire2learn.com/security/token/2007/08")]
        public AuthenticateResponse AuthenticateWithAppToken([System.Xml.Serialization.XmlElementAttribute(Namespace="http://desire2learn.com/security/token/2007/08")] AuthenticateWithAppTokenRequest AuthenticateWithAppTokenRequest) {
            object[] results = this.Invoke("AuthenticateWithAppToken", new object[] {
                        AuthenticateWithAppTokenRequest});
            return ((AuthenticateResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAuthenticateWithAppToken(AuthenticateWithAppTokenRequest AuthenticateWithAppTokenRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AuthenticateWithAppToken", new object[] {
                        AuthenticateWithAppTokenRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public AuthenticateResponse EndAuthenticateWithAppToken(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((AuthenticateResponse)(results[0]));
        }
        
        /// <remarks/>
        public void AuthenticateWithAppTokenAsync(AuthenticateWithAppTokenRequest AuthenticateWithAppTokenRequest) {
            this.AuthenticateWithAppTokenAsync(AuthenticateWithAppTokenRequest, null);
        }
        
        /// <remarks/>
        public void AuthenticateWithAppTokenAsync(AuthenticateWithAppTokenRequest AuthenticateWithAppTokenRequest, object userState) {
            if ((this.AuthenticateWithAppTokenOperationCompleted == null)) {
                this.AuthenticateWithAppTokenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenticateWithAppTokenOperationCompleted);
            }
            this.InvokeAsync("AuthenticateWithAppToken", new object[] {
                        AuthenticateWithAppTokenRequest}, this.AuthenticateWithAppTokenOperationCompleted, userState);
        }
        
        private void OnAuthenticateWithAppTokenOperationCompleted(object arg) {
            if ((this.AuthenticateWithAppTokenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthenticateWithAppTokenCompleted(this, new AuthenticateWithAppTokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://desire2learn.com/security/token/2007/08")]
    public partial class AuthenticateRequest {
        
        private string usernameField;
        
        private string passwordField;
        
        private string purposeField;
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string purpose {
            get {
                return this.purposeField;
            }
            set {
                this.purposeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://desire2learn.com/security/token/2007/08")]
    public partial class AuthenticateWithAppTokenRequest {
        
        private string usernameField;
        
        private string passwordField;
        
        private string purposeField;
        
        private string appTokenField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string Purpose {
            get {
                return this.purposeField;
            }
            set {
                this.purposeField = value;
            }
        }
        
        /// <remarks/>
        public string AppToken {
            get {
                return this.appTokenField;
            }
            set {
                this.appTokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://desire2learn.com/security/token/2007/08")]
    public partial class AuthenticateRequest2 {
        
        private string usernameField;
        
        private string passwordField;
        
        private string purposeField;
        
        private string devKeyField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string Purpose {
            get {
                return this.purposeField;
            }
            set {
                this.purposeField = value;
            }
        }
        
        /// <remarks/>
        public string DevKey {
            get {
                return this.devKeyField;
            }
            set {
                this.devKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://desire2learn.com/security/token/2007/08")]
    public partial class AuthenticationTokenSettings {
        
        private int maxUsageCountField;
        
        private int lifetimeInSecondsField;
        
        /// <remarks/>
        public int maxUsageCount {
            get {
                return this.maxUsageCountField;
            }
            set {
                this.maxUsageCountField = value;
            }
        }
        
        /// <remarks/>
        public int lifetimeInSeconds {
            get {
                return this.lifetimeInSecondsField;
            }
            set {
                this.lifetimeInSecondsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://desire2learn.com/security/token/2007/08")]
    public partial class AuthenticateResponse {
        
        private string tokenField;
        
        private AuthenticationStatus statusField;
        
        private AuthenticationTokenSettings tokenSettingsField;
        
        /// <remarks/>
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public AuthenticationStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public AuthenticationTokenSettings tokenSettings {
            get {
                return this.tokenSettingsField;
            }
            set {
                this.tokenSettingsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://desire2learn.com/security/token/2007/08")]
    public enum AuthenticationStatus {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Failure,
        
        /// <remarks/>
        Error,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    public delegate void AuthenticateCompletedEventHandler(object sender, AuthenticateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthenticateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthenticateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AuthenticateResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AuthenticateResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    public delegate void Authenticate2CompletedEventHandler(object sender, Authenticate2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Authenticate2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Authenticate2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AuthenticateResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AuthenticateResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    public delegate void AuthenticateWithAppTokenCompletedEventHandler(object sender, AuthenticateWithAppTokenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthenticateWithAppTokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthenticateWithAppTokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AuthenticateResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AuthenticateResponse)(this.results[0]));
            }
        }
    }
}
