using System;

namespace D2L.WS.Client.Proxy {
	public interface IGradesManagementServicev1_0 : IHeaderService {
		IAsyncResult BeginCreateNumericGradeItem( CreateNumericGradeItemRequest CreateNumericGradeItemRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginCreatePassFailGradeItem( CreatePassFailGradeItemRequest CreatePassFailGradeItemRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginCreateTextGradeItem( CreateTextGradeItemRequest CreateTextGradeItemRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginDeleteGradeItem( DeleteGradeItemRequest DeleteGradeItemRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetAdjustedFinalGradeItem( GetAdjustedFinalGradeItemRequest GetAdjustedFinalGradeItemRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetCalculatedFinalGradeItem( GetCalculatedFinalGradeItemRequest GetCalculatedFinalGradeItemRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetGradeObjectsByOrgUnit( GetGradeObjectsByOrgUnitRequest GetGradeObjectsByOrgUnitRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetGradeValueByGradeObjectUser( GetGradeValueByGradeObjectUserRequest GetGradeValueByGradeObjectUserRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetGradeValuesByGradeObject( GetGradeValuesByGradeObjectRequest GetGradeValuesByGradeObjectRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetGradeValuesByOrgUnit( GetGradeValuesByOrgUnitRequest GetGradeValuesByOrgUnitRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetGradeValuesByOrgUnitUser( GetGradeValuesByOrgUnitUserRequest GetGradeValuesByOrgUnitUserRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetGradeValuesByUser( GetGradeValuesByUserRequest GetGradeValuesByUserRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetNumericGradeItem( GetNumericGradeItemRequest GetNumericGradeItemRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetPassFailGradeItem( GetPassFailGradeItemRequest GetPassFailGradeItemRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetTextGradeItem( GetTextGradeItemRequest GetTextGradeItemRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginRecalculateCalculatedFinalGrade( RecalculateCalculatedFinalGradeRequest RecalculateCalculatedFinalGradeRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginSetAdjustedFinalGradeValue( SetAdjustedFinalGradeValueRequest SetAdjustedFinalGradeValueRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginSetNumericGradeValue( SetNumericGradeValueRequest SetNumericGradeValueRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginSetPassFailGradeValue( SetPassFailGradeValueRequest SetPassFailGradeValueRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginSetTextGradeValue( SetTextGradeValueRequest SetTextGradeValueRequest, AsyncCallback callback, object asyncState );
		void CancelAsync( object userState );
		CreateNumericGradeItemResponse CreateNumericGradeItem( CreateNumericGradeItemRequest CreateNumericGradeItemRequest );
		void CreateNumericGradeItemAsync( CreateNumericGradeItemRequest CreateNumericGradeItemRequest, object userState );
		void CreateNumericGradeItemAsync( CreateNumericGradeItemRequest CreateNumericGradeItemRequest );
		event CreateNumericGradeItemCompletedEventHandler CreateNumericGradeItemCompleted;
		CreatePassFailGradeItemResponse CreatePassFailGradeItem( CreatePassFailGradeItemRequest CreatePassFailGradeItemRequest );
		void CreatePassFailGradeItemAsync( CreatePassFailGradeItemRequest CreatePassFailGradeItemRequest );
		void CreatePassFailGradeItemAsync( CreatePassFailGradeItemRequest CreatePassFailGradeItemRequest, object userState );
		event CreatePassFailGradeItemCompletedEventHandler CreatePassFailGradeItemCompleted;
		CreateTextGradeItemResponse CreateTextGradeItem( CreateTextGradeItemRequest CreateTextGradeItemRequest );
		void CreateTextGradeItemAsync( CreateTextGradeItemRequest CreateTextGradeItemRequest, object userState );
		void CreateTextGradeItemAsync( CreateTextGradeItemRequest CreateTextGradeItemRequest );
		event CreateTextGradeItemCompletedEventHandler CreateTextGradeItemCompleted;
		DeleteGradeItemResponse DeleteGradeItem( DeleteGradeItemRequest DeleteGradeItemRequest );
		void DeleteGradeItemAsync( DeleteGradeItemRequest DeleteGradeItemRequest, object userState );
		void DeleteGradeItemAsync( DeleteGradeItemRequest DeleteGradeItemRequest );
		event DeleteGradeItemCompletedEventHandler DeleteGradeItemCompleted;
		CreateNumericGradeItemResponse EndCreateNumericGradeItem( IAsyncResult asyncResult );
		CreatePassFailGradeItemResponse EndCreatePassFailGradeItem( IAsyncResult asyncResult );
		CreateTextGradeItemResponse EndCreateTextGradeItem( IAsyncResult asyncResult );
		DeleteGradeItemResponse EndDeleteGradeItem( IAsyncResult asyncResult );
		GetAdjustedFinalGradeItemResponse EndGetAdjustedFinalGradeItem( IAsyncResult asyncResult );
		GetCalculatedFinalGradeItemResponse EndGetCalculatedFinalGradeItem( IAsyncResult asyncResult );
		GetGradeObjectsByOrgUnitResponse EndGetGradeObjectsByOrgUnit( IAsyncResult asyncResult );
		GetGradeValueByGradeObjectUserResponse EndGetGradeValueByGradeObjectUser( IAsyncResult asyncResult );
		GetGradeValuesByGradeObjectResponse EndGetGradeValuesByGradeObject( IAsyncResult asyncResult );
		GetGradeValuesByOrgUnitResponse EndGetGradeValuesByOrgUnit( IAsyncResult asyncResult );
		GetGradeValuesByOrgUnitUserResponse EndGetGradeValuesByOrgUnitUser( IAsyncResult asyncResult );
		GetGradeValuesByUserResponse EndGetGradeValuesByUser( IAsyncResult asyncResult );
		GetNumericGradeItemResponse EndGetNumericGradeItem( IAsyncResult asyncResult );
		GetPassFailGradeItemResponse EndGetPassFailGradeItem( IAsyncResult asyncResult );
		GetTextGradeItemResponse EndGetTextGradeItem( IAsyncResult asyncResult );
		RecalculateCalculatedFinalGradeResponse EndRecalculateCalculatedFinalGrade( IAsyncResult asyncResult );
		SetGradeValueResponse EndSetAdjustedFinalGradeValue( IAsyncResult asyncResult );
		SetGradeValueResponse EndSetNumericGradeValue( IAsyncResult asyncResult );
		SetGradeValueResponse EndSetPassFailGradeValue( IAsyncResult asyncResult );
		SetGradeValueResponse EndSetTextGradeValue( IAsyncResult asyncResult );
		GetAdjustedFinalGradeItemResponse GetAdjustedFinalGradeItem( GetAdjustedFinalGradeItemRequest GetAdjustedFinalGradeItemRequest );
		void GetAdjustedFinalGradeItemAsync( GetAdjustedFinalGradeItemRequest GetAdjustedFinalGradeItemRequest );
		void GetAdjustedFinalGradeItemAsync( GetAdjustedFinalGradeItemRequest GetAdjustedFinalGradeItemRequest, object userState );
		event GetAdjustedFinalGradeItemCompletedEventHandler GetAdjustedFinalGradeItemCompleted;
		GetCalculatedFinalGradeItemResponse GetCalculatedFinalGradeItem( GetCalculatedFinalGradeItemRequest GetCalculatedFinalGradeItemRequest );
		void GetCalculatedFinalGradeItemAsync( GetCalculatedFinalGradeItemRequest GetCalculatedFinalGradeItemRequest, object userState );
		void GetCalculatedFinalGradeItemAsync( GetCalculatedFinalGradeItemRequest GetCalculatedFinalGradeItemRequest );
		event GetCalculatedFinalGradeItemCompletedEventHandler GetCalculatedFinalGradeItemCompleted;
		GetGradeObjectsByOrgUnitResponse GetGradeObjectsByOrgUnit( GetGradeObjectsByOrgUnitRequest GetGradeObjectsByOrgUnitRequest );
		void GetGradeObjectsByOrgUnitAsync( GetGradeObjectsByOrgUnitRequest GetGradeObjectsByOrgUnitRequest, object userState );
		void GetGradeObjectsByOrgUnitAsync( GetGradeObjectsByOrgUnitRequest GetGradeObjectsByOrgUnitRequest );
		event GetGradeObjectsByOrgUnitCompletedEventHandler GetGradeObjectsByOrgUnitCompleted;
		GetGradeValueByGradeObjectUserResponse GetGradeValueByGradeObjectUser( GetGradeValueByGradeObjectUserRequest GetGradeValueByGradeObjectUserRequest );
		void GetGradeValueByGradeObjectUserAsync( GetGradeValueByGradeObjectUserRequest GetGradeValueByGradeObjectUserRequest );
		void GetGradeValueByGradeObjectUserAsync( GetGradeValueByGradeObjectUserRequest GetGradeValueByGradeObjectUserRequest, object userState );
		event GetGradeValueByGradeObjectUserCompletedEventHandler GetGradeValueByGradeObjectUserCompleted;
		GetGradeValuesByGradeObjectResponse GetGradeValuesByGradeObject( GetGradeValuesByGradeObjectRequest GetGradeValuesByGradeObjectRequest );
		void GetGradeValuesByGradeObjectAsync( GetGradeValuesByGradeObjectRequest GetGradeValuesByGradeObjectRequest, object userState );
		void GetGradeValuesByGradeObjectAsync( GetGradeValuesByGradeObjectRequest GetGradeValuesByGradeObjectRequest );
		event GetGradeValuesByGradeObjectCompletedEventHandler GetGradeValuesByGradeObjectCompleted;
		GetGradeValuesByOrgUnitResponse GetGradeValuesByOrgUnit( GetGradeValuesByOrgUnitRequest GetGradeValuesByOrgUnitRequest );
		void GetGradeValuesByOrgUnitAsync( GetGradeValuesByOrgUnitRequest GetGradeValuesByOrgUnitRequest, object userState );
		void GetGradeValuesByOrgUnitAsync( GetGradeValuesByOrgUnitRequest GetGradeValuesByOrgUnitRequest );
		event GetGradeValuesByOrgUnitCompletedEventHandler GetGradeValuesByOrgUnitCompleted;
		GetGradeValuesByOrgUnitUserResponse GetGradeValuesByOrgUnitUser( GetGradeValuesByOrgUnitUserRequest GetGradeValuesByOrgUnitUserRequest );
		void GetGradeValuesByOrgUnitUserAsync( GetGradeValuesByOrgUnitUserRequest GetGradeValuesByOrgUnitUserRequest );
		void GetGradeValuesByOrgUnitUserAsync( GetGradeValuesByOrgUnitUserRequest GetGradeValuesByOrgUnitUserRequest, object userState );
		event GetGradeValuesByOrgUnitUserCompletedEventHandler GetGradeValuesByOrgUnitUserCompleted;
		GetGradeValuesByUserResponse GetGradeValuesByUser( GetGradeValuesByUserRequest GetGradeValuesByUserRequest );
		void GetGradeValuesByUserAsync( GetGradeValuesByUserRequest GetGradeValuesByUserRequest, object userState );
		void GetGradeValuesByUserAsync( GetGradeValuesByUserRequest GetGradeValuesByUserRequest );
		event GetGradeValuesByUserCompletedEventHandler GetGradeValuesByUserCompleted;
		GetNumericGradeItemResponse GetNumericGradeItem( GetNumericGradeItemRequest GetNumericGradeItemRequest );
		void GetNumericGradeItemAsync( GetNumericGradeItemRequest GetNumericGradeItemRequest );
		void GetNumericGradeItemAsync( GetNumericGradeItemRequest GetNumericGradeItemRequest, object userState );
		event GetNumericGradeItemCompletedEventHandler GetNumericGradeItemCompleted;
		GetPassFailGradeItemResponse GetPassFailGradeItem( GetPassFailGradeItemRequest GetPassFailGradeItemRequest );
		void GetPassFailGradeItemAsync( GetPassFailGradeItemRequest GetPassFailGradeItemRequest, object userState );
		void GetPassFailGradeItemAsync( GetPassFailGradeItemRequest GetPassFailGradeItemRequest );
		event GetPassFailGradeItemCompletedEventHandler GetPassFailGradeItemCompleted;
		GetTextGradeItemResponse GetTextGradeItem( GetTextGradeItemRequest GetTextGradeItemRequest );
		void GetTextGradeItemAsync( GetTextGradeItemRequest GetTextGradeItemRequest );
		void GetTextGradeItemAsync( GetTextGradeItemRequest GetTextGradeItemRequest, object userState );
		event GetTextGradeItemCompletedEventHandler GetTextGradeItemCompleted;
		RecalculateCalculatedFinalGradeResponse RecalculateCalculatedFinalGrade( RecalculateCalculatedFinalGradeRequest RecalculateCalculatedFinalGradeRequest );
		void RecalculateCalculatedFinalGradeAsync( RecalculateCalculatedFinalGradeRequest RecalculateCalculatedFinalGradeRequest, object userState );
		void RecalculateCalculatedFinalGradeAsync( RecalculateCalculatedFinalGradeRequest RecalculateCalculatedFinalGradeRequest );
		event RecalculateCalculatedFinalGradeCompletedEventHandler RecalculateCalculatedFinalGradeCompleted;
		SetGradeValueResponse SetAdjustedFinalGradeValue( SetAdjustedFinalGradeValueRequest SetAdjustedFinalGradeValueRequest );
		void SetAdjustedFinalGradeValueAsync( SetAdjustedFinalGradeValueRequest SetAdjustedFinalGradeValueRequest );
		void SetAdjustedFinalGradeValueAsync( SetAdjustedFinalGradeValueRequest SetAdjustedFinalGradeValueRequest, object userState );
		event SetAdjustedFinalGradeValueCompletedEventHandler SetAdjustedFinalGradeValueCompleted;
		SetGradeValueResponse SetNumericGradeValue( SetNumericGradeValueRequest SetNumericGradeValueRequest );
		void SetNumericGradeValueAsync( SetNumericGradeValueRequest SetNumericGradeValueRequest, object userState );
		void SetNumericGradeValueAsync( SetNumericGradeValueRequest SetNumericGradeValueRequest );
		event SetNumericGradeValueCompletedEventHandler SetNumericGradeValueCompleted;
		SetGradeValueResponse SetPassFailGradeValue( SetPassFailGradeValueRequest SetPassFailGradeValueRequest );
		void SetPassFailGradeValueAsync( SetPassFailGradeValueRequest SetPassFailGradeValueRequest );
		void SetPassFailGradeValueAsync( SetPassFailGradeValueRequest SetPassFailGradeValueRequest, object userState );
		event SetPassFailGradeValueCompletedEventHandler SetPassFailGradeValueCompleted;
		SetGradeValueResponse SetTextGradeValue( SetTextGradeValueRequest SetTextGradeValueRequest );
		void SetTextGradeValueAsync( SetTextGradeValueRequest SetTextGradeValueRequest, object userState );
		void SetTextGradeValueAsync( SetTextGradeValueRequest SetTextGradeValueRequest );
		event SetTextGradeValueCompletedEventHandler SetTextGradeValueCompleted;
	}
}
