using System;

namespace D2L.WS.Client.Proxy {
	public interface IOrgUnitManagementServicev1_0 : IHeaderService {
		AddChildOrgUnitResponse AddChildOrgUnit( AddChildOrgUnitRequest AddChildOrgUnitRequest );
		void AddChildOrgUnitAsync( AddChildOrgUnitRequest AddChildOrgUnitRequest, object userState );
		void AddChildOrgUnitAsync( AddChildOrgUnitRequest AddChildOrgUnitRequest );
		event AddChildOrgUnitCompletedEventHandler AddChildOrgUnitCompleted;
		IAsyncResult BeginAddChildOrgUnit( AddChildOrgUnitRequest AddChildOrgUnitRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginCreateCourseOffering( CreateCourseOfferingRequest CreateCourseOfferingRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginCreateCourseTemplate( CreateCourseTemplateRequest CreateCourseTemplateRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginCreateCustomOrgUnit( CreateCustomOrgUnitRequest CreateCustomOrgUnitRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginCreateCustomOrgUnitType( CreateCustomOrgUnitTypeRequest CreateCustomOrgUnitTypeRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginCreateDepartment( CreateDepartmentRequest CreateDepartmentRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginCreateGroup( CreateGroupRequest CreateGroupRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginCreateGroupType( CreateGroupTypeRequest CreateGroupTypeRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginCreateSection( CreateSectionRequest CreateSectionRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginCreateSemester( CreateSemesterRequest CreateSemesterRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginDeleteCourseOffering( DeleteCourseOfferingRequest DeleteCourseOfferingRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginDeleteCourseTemplate( DeleteCourseTemplateRequest DeleteCourseTemplateRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginDeleteCustomOrgUnit( DeleteCustomOrgUnitRequest DeleteCustomOrgUnitRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginDeleteCustomOrgUnitType( DeleteCustomOrgUnitTypeRequest DeleteCustomOrgUnitTypeRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginDeleteDepartment( DeleteDepartmentRequest DeleteDepartmentRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginDeleteGroup( DeleteGroupRequest DeleteGroupRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginDeleteGroupType( DeleteGroupTypeRequest DeleteGroupTypeRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginDeleteSection( DeleteSectionRequest DeleteSectionRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginDeleteSemester( DeleteSemesterRequest DeleteSemesterRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetChildCourseOfferings( GetChildCourseOfferingsRequest GetChildCourseOfferingsRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetChildCourseTemplates( GetChildCourseTemplatesRequest GetChildCourseTemplatesRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetChildCustomOrgUnits( GetChildCustomOrgUnitsRequest GetChildCustomOrgUnitsRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetChildCustomOrgUnitsByType( GetChildCustomOrgUnitsByTypeRequest GetChildCustomOrgUnitsByTypeRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetChildDepartments( GetChildDepartmentsRequest GetChildDepartmentsRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetChildGroups( GetChildGroupsRequest GetChildGroupsRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetChildGroupsByType( GetChildGroupsByTypeRequest GetChildGroupsByTypeRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetChildOrgUnitIds( GetChildOrgUnitIdsRequest GetChildOrgUnitIdsRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetChildOrgUnitTypeIds( GetChildOrgUnitTypeIdsRequest GetChildOrgUnitTypeIdsRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetChildSections( GetChildSectionsRequest GetChildSectionsRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetChildSemesters( GetChildSemestersRequest GetChildSemestersRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetCourseOffering( GetCourseOfferingRequest GetCourseOfferingRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetCourseOfferingByCode( GetCourseOfferingByCodeRequest GetCourseOfferingByCodeRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetCourseTemplate( GetCourseTemplateRequest GetCourseTemplateRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetCourseTemplateByCode( GetCourseTemplateByCodeRequest GetCourseTemplateByCodeRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetCustomOrgUnit( GetCustomOrgUnitRequest GetCustomOrgUnitRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetCustomOrgUnitByCode( GetCustomOrgUnitByCodeRequest GetCustomOrgUnitByCodeRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetCustomOrgUnitType( GetCustomOrgUnitTypeRequest GetCustomOrgUnitTypeRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetCustomOrgUnitTypes( GetCustomOrgUnitTypesRequest GetCustomOrgUnitTypesRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetDepartment( GetDepartmentRequest GetDepartmentRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetDepartmentByCode( GetDepartmentByCodeRequest GetDepartmentByCodeRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetDepartmentOrgUnitType( GetDepartmentOrgUnitTypeRequest GetDepartmentOrgUnitTypeRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetGroup( GetGroupRequest GetGroupRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetGroupByCode( GetGroupByCodeRequest GetGroupByCodeRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetGroupType( GetGroupTypeRequest GetGroupTypeRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetGroupTypes( GetGroupTypesRequest GetGroupTypesRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetOrganization( GetOrganizationRequest GetOrganizationRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetParentOrgUnitIds( GetParentOrgUnitIdsRequest GetParentOrgUnitIdsRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetSection( GetSectionRequest GetSectionRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetSectionByCode( GetSectionByCodeRequest GetSectionByCodeRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetSemester( GetSemesterRequest GetSemesterRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetSemesterByCode( GetSemesterByCodeRequest GetSemesterByCodeRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetSemesterOrgUnitType( GetSemesterOrgUnitTypeRequest GetSemesterOrgUnitTypeRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginGetSystemOrgUnitTypes( GetSystemOrgUnitTypesRequest GetStandardOrgUnitTypesRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginRemoveChildOrgUnit( RemoveChildOrgUnitRequest RemoveChildOrgUnitRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginUpdateCourseOffering( UpdateCourseOfferingRequest UpdateCourseOfferingRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginUpdateCourseTemplate( UpdateCourseTemplateRequest UpdateCourseTemplateRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginUpdateCustomOrgUnit( UpdateCustomOrgUnitRequest UpdateCustomOrgUnitRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginUpdateCustomOrgUnitType( UpdateCustomOrgUnitTypeRequest UpdateCustomOrgUnitTypeRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginUpdateDepartment( UpdateDepartmentRequest UpdateDepartmentRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginUpdateGroup( UpdateGroupRequest UpdateGroupRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginUpdateGroupType( UpdateGroupTypeRequest UpdateGroupTypeRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginUpdateSection( UpdateSectionRequest UpdateSectionRequest, AsyncCallback callback, object asyncState );
		IAsyncResult BeginUpdateSemester( UpdateSemesterRequest UpdateSemesterRequest, AsyncCallback callback, object asyncState );
		void CancelAsync( object userState );
		CreateCourseOfferingResponse CreateCourseOffering( CreateCourseOfferingRequest CreateCourseOfferingRequest );
		void CreateCourseOfferingAsync( CreateCourseOfferingRequest CreateCourseOfferingRequest );
		void CreateCourseOfferingAsync( CreateCourseOfferingRequest CreateCourseOfferingRequest, object userState );
		event CreateCourseOfferingCompletedEventHandler CreateCourseOfferingCompleted;
		CreateCourseTemplateResponse CreateCourseTemplate( CreateCourseTemplateRequest CreateCourseTemplateRequest );
		void CreateCourseTemplateAsync( CreateCourseTemplateRequest CreateCourseTemplateRequest, object userState );
		void CreateCourseTemplateAsync( CreateCourseTemplateRequest CreateCourseTemplateRequest );
		event CreateCourseTemplateCompletedEventHandler CreateCourseTemplateCompleted;
		CreateCustomOrgUnitResponse CreateCustomOrgUnit( CreateCustomOrgUnitRequest CreateCustomOrgUnitRequest );
		void CreateCustomOrgUnitAsync( CreateCustomOrgUnitRequest CreateCustomOrgUnitRequest, object userState );
		void CreateCustomOrgUnitAsync( CreateCustomOrgUnitRequest CreateCustomOrgUnitRequest );
		event CreateCustomOrgUnitCompletedEventHandler CreateCustomOrgUnitCompleted;
		CreateCustomOrgUnitTypeResponse CreateCustomOrgUnitType( CreateCustomOrgUnitTypeRequest CreateCustomOrgUnitTypeRequest );
		void CreateCustomOrgUnitTypeAsync( CreateCustomOrgUnitTypeRequest CreateCustomOrgUnitTypeRequest );
		void CreateCustomOrgUnitTypeAsync( CreateCustomOrgUnitTypeRequest CreateCustomOrgUnitTypeRequest, object userState );
		event CreateCustomOrgUnitTypeCompletedEventHandler CreateCustomOrgUnitTypeCompleted;
		CreateDepartmentResponse CreateDepartment( CreateDepartmentRequest CreateDepartmentRequest );
		void CreateDepartmentAsync( CreateDepartmentRequest CreateDepartmentRequest );
		void CreateDepartmentAsync( CreateDepartmentRequest CreateDepartmentRequest, object userState );
		event CreateDepartmentCompletedEventHandler CreateDepartmentCompleted;
		CreateGroupResponse CreateGroup( CreateGroupRequest CreateGroupRequest );
		void CreateGroupAsync( CreateGroupRequest CreateGroupRequest, object userState );
		void CreateGroupAsync( CreateGroupRequest CreateGroupRequest );
		event CreateGroupCompletedEventHandler CreateGroupCompleted;
		CreateGroupTypeResponse CreateGroupType( CreateGroupTypeRequest CreateGroupTypeRequest );
		void CreateGroupTypeAsync( CreateGroupTypeRequest CreateGroupTypeRequest );
		void CreateGroupTypeAsync( CreateGroupTypeRequest CreateGroupTypeRequest, object userState );
		event CreateGroupTypeCompletedEventHandler CreateGroupTypeCompleted;
		CreateSectionResponse CreateSection( CreateSectionRequest CreateSectionRequest );
		void CreateSectionAsync( CreateSectionRequest CreateSectionRequest );
		void CreateSectionAsync( CreateSectionRequest CreateSectionRequest, object userState );
		event CreateSectionCompletedEventHandler CreateSectionCompleted;
		CreateSemesterResponse CreateSemester( CreateSemesterRequest CreateSemesterRequest );
		void CreateSemesterAsync( CreateSemesterRequest CreateSemesterRequest );
		void CreateSemesterAsync( CreateSemesterRequest CreateSemesterRequest, object userState );
		event CreateSemesterCompletedEventHandler CreateSemesterCompleted;
		DeleteOrgUnitResponse DeleteCourseOffering( DeleteCourseOfferingRequest DeleteCourseOfferingRequest );
		void DeleteCourseOfferingAsync( DeleteCourseOfferingRequest DeleteCourseOfferingRequest, object userState );
		void DeleteCourseOfferingAsync( DeleteCourseOfferingRequest DeleteCourseOfferingRequest );
		event DeleteCourseOfferingCompletedEventHandler DeleteCourseOfferingCompleted;
		DeleteOrgUnitResponse DeleteCourseTemplate( DeleteCourseTemplateRequest DeleteCourseTemplateRequest );
		void DeleteCourseTemplateAsync( DeleteCourseTemplateRequest DeleteCourseTemplateRequest );
		void DeleteCourseTemplateAsync( DeleteCourseTemplateRequest DeleteCourseTemplateRequest, object userState );
		event DeleteCourseTemplateCompletedEventHandler DeleteCourseTemplateCompleted;
		DeleteOrgUnitResponse DeleteCustomOrgUnit( DeleteCustomOrgUnitRequest DeleteCustomOrgUnitRequest );
		void DeleteCustomOrgUnitAsync( DeleteCustomOrgUnitRequest DeleteCustomOrgUnitRequest, object userState );
		void DeleteCustomOrgUnitAsync( DeleteCustomOrgUnitRequest DeleteCustomOrgUnitRequest );
		event DeleteCustomOrgUnitCompletedEventHandler DeleteCustomOrgUnitCompleted;
		DeleteCustomOrgUnitTypeResponse DeleteCustomOrgUnitType( DeleteCustomOrgUnitTypeRequest DeleteCustomOrgUnitTypeRequest );
		void DeleteCustomOrgUnitTypeAsync( DeleteCustomOrgUnitTypeRequest DeleteCustomOrgUnitTypeRequest, object userState );
		void DeleteCustomOrgUnitTypeAsync( DeleteCustomOrgUnitTypeRequest DeleteCustomOrgUnitTypeRequest );
		event DeleteCustomOrgUnitTypeCompletedEventHandler DeleteCustomOrgUnitTypeCompleted;
		DeleteOrgUnitResponse DeleteDepartment( DeleteDepartmentRequest DeleteDepartmentRequest );
		void DeleteDepartmentAsync( DeleteDepartmentRequest DeleteDepartmentRequest );
		void DeleteDepartmentAsync( DeleteDepartmentRequest DeleteDepartmentRequest, object userState );
		event DeleteDepartmentCompletedEventHandler DeleteDepartmentCompleted;
		DeleteOrgUnitResponse DeleteGroup( DeleteGroupRequest DeleteGroupRequest );
		void DeleteGroupAsync( DeleteGroupRequest DeleteGroupRequest );
		void DeleteGroupAsync( DeleteGroupRequest DeleteGroupRequest, object userState );
		event DeleteGroupCompletedEventHandler DeleteGroupCompleted;
		DeleteGroupTypeResponse DeleteGroupType( DeleteGroupTypeRequest DeleteGroupTypeRequest );
		void DeleteGroupTypeAsync( DeleteGroupTypeRequest DeleteGroupTypeRequest, object userState );
		void DeleteGroupTypeAsync( DeleteGroupTypeRequest DeleteGroupTypeRequest );
		event DeleteGroupTypeCompletedEventHandler DeleteGroupTypeCompleted;
		DeleteOrgUnitResponse DeleteSection( DeleteSectionRequest DeleteSectionRequest );
		void DeleteSectionAsync( DeleteSectionRequest DeleteSectionRequest, object userState );
		void DeleteSectionAsync( DeleteSectionRequest DeleteSectionRequest );
		event DeleteSectionCompletedEventHandler DeleteSectionCompleted;
		DeleteOrgUnitResponse DeleteSemester( DeleteSemesterRequest DeleteSemesterRequest );
		void DeleteSemesterAsync( DeleteSemesterRequest DeleteSemesterRequest );
		void DeleteSemesterAsync( DeleteSemesterRequest DeleteSemesterRequest, object userState );
		event DeleteSemesterCompletedEventHandler DeleteSemesterCompleted;
		AddChildOrgUnitResponse EndAddChildOrgUnit( IAsyncResult asyncResult );
		CreateCourseOfferingResponse EndCreateCourseOffering( IAsyncResult asyncResult );
		CreateCourseTemplateResponse EndCreateCourseTemplate( IAsyncResult asyncResult );
		CreateCustomOrgUnitResponse EndCreateCustomOrgUnit( IAsyncResult asyncResult );
		CreateCustomOrgUnitTypeResponse EndCreateCustomOrgUnitType( IAsyncResult asyncResult );
		CreateDepartmentResponse EndCreateDepartment( IAsyncResult asyncResult );
		CreateGroupResponse EndCreateGroup( IAsyncResult asyncResult );
		CreateGroupTypeResponse EndCreateGroupType( IAsyncResult asyncResult );
		CreateSectionResponse EndCreateSection( IAsyncResult asyncResult );
		CreateSemesterResponse EndCreateSemester( IAsyncResult asyncResult );
		DeleteOrgUnitResponse EndDeleteCourseOffering( IAsyncResult asyncResult );
		DeleteOrgUnitResponse EndDeleteCourseTemplate( IAsyncResult asyncResult );
		DeleteOrgUnitResponse EndDeleteCustomOrgUnit( IAsyncResult asyncResult );
		DeleteCustomOrgUnitTypeResponse EndDeleteCustomOrgUnitType( IAsyncResult asyncResult );
		DeleteOrgUnitResponse EndDeleteDepartment( IAsyncResult asyncResult );
		DeleteOrgUnitResponse EndDeleteGroup( IAsyncResult asyncResult );
		DeleteGroupTypeResponse EndDeleteGroupType( IAsyncResult asyncResult );
		DeleteOrgUnitResponse EndDeleteSection( IAsyncResult asyncResult );
		DeleteOrgUnitResponse EndDeleteSemester( IAsyncResult asyncResult );
		GetCourseOfferingsResponse EndGetChildCourseOfferings( IAsyncResult asyncResult );
		GetCourseTemplatesResponse EndGetChildCourseTemplates( IAsyncResult asyncResult );
		GetCustomOrgUnitsResponse EndGetChildCustomOrgUnits( IAsyncResult asyncResult );
		GetCustomOrgUnitsResponse EndGetChildCustomOrgUnitsByType( IAsyncResult asyncResult );
		GetDepartmentsResponse EndGetChildDepartments( IAsyncResult asyncResult );
		GetGroupsResponse EndGetChildGroups( IAsyncResult asyncResult );
		GetGroupsResponse EndGetChildGroupsByType( IAsyncResult asyncResult );
		GetOrgUnitIdsResponse EndGetChildOrgUnitIds( IAsyncResult asyncResult );
		GetChildOrgUnitTypeIdsResponse EndGetChildOrgUnitTypeIds( IAsyncResult asyncResult );
		GetSectionsResponse EndGetChildSections( IAsyncResult asyncResult );
		GetSemestersResponse EndGetChildSemesters( IAsyncResult asyncResult );
		GetCourseOfferingResponse EndGetCourseOffering( IAsyncResult asyncResult );
		GetCourseOfferingResponse EndGetCourseOfferingByCode( IAsyncResult asyncResult );
		GetCourseTemplateResponse EndGetCourseTemplate( IAsyncResult asyncResult );
		GetCourseTemplateResponse EndGetCourseTemplateByCode( IAsyncResult asyncResult );
		GetCustomOrgUnitResponse EndGetCustomOrgUnit( IAsyncResult asyncResult );
		GetCustomOrgUnitResponse EndGetCustomOrgUnitByCode( IAsyncResult asyncResult );
		GetCustomOrgUnitTypeResponse EndGetCustomOrgUnitType( IAsyncResult asyncResult );
		GetCustomOrgUnitTypesResponse EndGetCustomOrgUnitTypes( IAsyncResult asyncResult );
		GetDepartmentResponse EndGetDepartment( IAsyncResult asyncResult );
		GetDepartmentResponse EndGetDepartmentByCode( IAsyncResult asyncResult );
		GetDepartmentOrgUnitTypeResponse EndGetDepartmentOrgUnitType( IAsyncResult asyncResult );
		GetGroupResponse EndGetGroup( IAsyncResult asyncResult );
		GetGroupResponse EndGetGroupByCode( IAsyncResult asyncResult );
		GetGroupTypeResponse EndGetGroupType( IAsyncResult asyncResult );
		GetGroupTypesResponse EndGetGroupTypes( IAsyncResult asyncResult );
		GetOrganizationResponse EndGetOrganization( IAsyncResult asyncResult );
		GetOrgUnitIdsResponse EndGetParentOrgUnitIds( IAsyncResult asyncResult );
		GetSectionResponse EndGetSection( IAsyncResult asyncResult );
		GetSectionResponse EndGetSectionByCode( IAsyncResult asyncResult );
		GetSemesterResponse EndGetSemester( IAsyncResult asyncResult );
		GetSemesterResponse EndGetSemesterByCode( IAsyncResult asyncResult );
		GetSemesterOrgUnitTypeResponse EndGetSemesterOrgUnitType( IAsyncResult asyncResult );
		GetSystemOrgUnitTypesResponse EndGetSystemOrgUnitTypes( IAsyncResult asyncResult );
		RemoveChildOrgUnitResponse EndRemoveChildOrgUnit( IAsyncResult asyncResult );
		UpdateOrgUnitResponse EndUpdateCourseOffering( IAsyncResult asyncResult );
		UpdateOrgUnitResponse EndUpdateCourseTemplate( IAsyncResult asyncResult );
		UpdateOrgUnitResponse EndUpdateCustomOrgUnit( IAsyncResult asyncResult );
		UpdateCustomOrgUnitTypeResponse EndUpdateCustomOrgUnitType( IAsyncResult asyncResult );
		UpdateOrgUnitResponse EndUpdateDepartment( IAsyncResult asyncResult );
		UpdateOrgUnitResponse EndUpdateGroup( IAsyncResult asyncResult );
		UpdateGroupTypeResponse EndUpdateGroupType( IAsyncResult asyncResult );
		UpdateOrgUnitResponse EndUpdateSection( IAsyncResult asyncResult );
		UpdateOrgUnitResponse EndUpdateSemester( IAsyncResult asyncResult );
		GetCourseOfferingsResponse GetChildCourseOfferings( GetChildCourseOfferingsRequest GetChildCourseOfferingsRequest );
		void GetChildCourseOfferingsAsync( GetChildCourseOfferingsRequest GetChildCourseOfferingsRequest, object userState );
		void GetChildCourseOfferingsAsync( GetChildCourseOfferingsRequest GetChildCourseOfferingsRequest );
		event GetChildCourseOfferingsCompletedEventHandler GetChildCourseOfferingsCompleted;
		GetCourseTemplatesResponse GetChildCourseTemplates( GetChildCourseTemplatesRequest GetChildCourseTemplatesRequest );
		void GetChildCourseTemplatesAsync( GetChildCourseTemplatesRequest GetChildCourseTemplatesRequest );
		void GetChildCourseTemplatesAsync( GetChildCourseTemplatesRequest GetChildCourseTemplatesRequest, object userState );
		event GetChildCourseTemplatesCompletedEventHandler GetChildCourseTemplatesCompleted;
		GetCustomOrgUnitsResponse GetChildCustomOrgUnits( GetChildCustomOrgUnitsRequest GetChildCustomOrgUnitsRequest );
		void GetChildCustomOrgUnitsAsync( GetChildCustomOrgUnitsRequest GetChildCustomOrgUnitsRequest, object userState );
		void GetChildCustomOrgUnitsAsync( GetChildCustomOrgUnitsRequest GetChildCustomOrgUnitsRequest );
		GetCustomOrgUnitsResponse GetChildCustomOrgUnitsByType( GetChildCustomOrgUnitsByTypeRequest GetChildCustomOrgUnitsByTypeRequest );
		void GetChildCustomOrgUnitsByTypeAsync( GetChildCustomOrgUnitsByTypeRequest GetChildCustomOrgUnitsByTypeRequest );
		void GetChildCustomOrgUnitsByTypeAsync( GetChildCustomOrgUnitsByTypeRequest GetChildCustomOrgUnitsByTypeRequest, object userState );
		event GetChildCustomOrgUnitsByTypeCompletedEventHandler GetChildCustomOrgUnitsByTypeCompleted;
		event GetChildCustomOrgUnitsCompletedEventHandler GetChildCustomOrgUnitsCompleted;
		GetDepartmentsResponse GetChildDepartments( GetChildDepartmentsRequest GetChildDepartmentsRequest );
		void GetChildDepartmentsAsync( GetChildDepartmentsRequest GetChildDepartmentsRequest );
		void GetChildDepartmentsAsync( GetChildDepartmentsRequest GetChildDepartmentsRequest, object userState );
		event GetChildDepartmentsCompletedEventHandler GetChildDepartmentsCompleted;
		GetGroupsResponse GetChildGroups( GetChildGroupsRequest GetChildGroupsRequest );
		void GetChildGroupsAsync( GetChildGroupsRequest GetChildGroupsRequest );
		void GetChildGroupsAsync( GetChildGroupsRequest GetChildGroupsRequest, object userState );
		GetGroupsResponse GetChildGroupsByType( GetChildGroupsByTypeRequest GetChildGroupsByTypeRequest );
		void GetChildGroupsByTypeAsync( GetChildGroupsByTypeRequest GetChildGroupsByTypeRequest, object userState );
		void GetChildGroupsByTypeAsync( GetChildGroupsByTypeRequest GetChildGroupsByTypeRequest );
		event GetChildGroupsByTypeCompletedEventHandler GetChildGroupsByTypeCompleted;
		event GetChildGroupsCompletedEventHandler GetChildGroupsCompleted;
		GetOrgUnitIdsResponse GetChildOrgUnitIds( GetChildOrgUnitIdsRequest GetChildOrgUnitIdsRequest );
		void GetChildOrgUnitIdsAsync( GetChildOrgUnitIdsRequest GetChildOrgUnitIdsRequest );
		void GetChildOrgUnitIdsAsync( GetChildOrgUnitIdsRequest GetChildOrgUnitIdsRequest, object userState );
		event GetChildOrgUnitIdsCompletedEventHandler GetChildOrgUnitIdsCompleted;
		GetChildOrgUnitTypeIdsResponse GetChildOrgUnitTypeIds( GetChildOrgUnitTypeIdsRequest GetChildOrgUnitTypeIdsRequest );
		void GetChildOrgUnitTypeIdsAsync( GetChildOrgUnitTypeIdsRequest GetChildOrgUnitTypeIdsRequest );
		void GetChildOrgUnitTypeIdsAsync( GetChildOrgUnitTypeIdsRequest GetChildOrgUnitTypeIdsRequest, object userState );
		event GetChildOrgUnitTypeIdsCompletedEventHandler GetChildOrgUnitTypeIdsCompleted;
		GetSectionsResponse GetChildSections( GetChildSectionsRequest GetChildSectionsRequest );
		void GetChildSectionsAsync( GetChildSectionsRequest GetChildSectionsRequest );
		void GetChildSectionsAsync( GetChildSectionsRequest GetChildSectionsRequest, object userState );
		event GetChildSectionsCompletedEventHandler GetChildSectionsCompleted;
		GetSemestersResponse GetChildSemesters( GetChildSemestersRequest GetChildSemestersRequest );
		void GetChildSemestersAsync( GetChildSemestersRequest GetChildSemestersRequest, object userState );
		void GetChildSemestersAsync( GetChildSemestersRequest GetChildSemestersRequest );
		event GetChildSemestersCompletedEventHandler GetChildSemestersCompleted;
		GetCourseOfferingResponse GetCourseOffering( GetCourseOfferingRequest GetCourseOfferingRequest );
		void GetCourseOfferingAsync( GetCourseOfferingRequest GetCourseOfferingRequest, object userState );
		void GetCourseOfferingAsync( GetCourseOfferingRequest GetCourseOfferingRequest );
		GetCourseOfferingResponse GetCourseOfferingByCode( GetCourseOfferingByCodeRequest GetCourseOfferingByCodeRequest );
		void GetCourseOfferingByCodeAsync( GetCourseOfferingByCodeRequest GetCourseOfferingByCodeRequest, object userState );
		void GetCourseOfferingByCodeAsync( GetCourseOfferingByCodeRequest GetCourseOfferingByCodeRequest );
		event GetCourseOfferingByCodeCompletedEventHandler GetCourseOfferingByCodeCompleted;
		event GetCourseOfferingCompletedEventHandler GetCourseOfferingCompleted;
		GetCourseTemplateResponse GetCourseTemplate( GetCourseTemplateRequest GetCourseTemplateRequest );
		void GetCourseTemplateAsync( GetCourseTemplateRequest GetCourseTemplateRequest );
		void GetCourseTemplateAsync( GetCourseTemplateRequest GetCourseTemplateRequest, object userState );
		GetCourseTemplateResponse GetCourseTemplateByCode( GetCourseTemplateByCodeRequest GetCourseTemplateByCodeRequest );
		void GetCourseTemplateByCodeAsync( GetCourseTemplateByCodeRequest GetCourseTemplateByCodeRequest );
		void GetCourseTemplateByCodeAsync( GetCourseTemplateByCodeRequest GetCourseTemplateByCodeRequest, object userState );
		event GetCourseTemplateByCodeCompletedEventHandler GetCourseTemplateByCodeCompleted;
		event GetCourseTemplateCompletedEventHandler GetCourseTemplateCompleted;
		GetCustomOrgUnitResponse GetCustomOrgUnit( GetCustomOrgUnitRequest GetCustomOrgUnitRequest );
		void GetCustomOrgUnitAsync( GetCustomOrgUnitRequest GetCustomOrgUnitRequest, object userState );
		void GetCustomOrgUnitAsync( GetCustomOrgUnitRequest GetCustomOrgUnitRequest );
		GetCustomOrgUnitResponse GetCustomOrgUnitByCode( GetCustomOrgUnitByCodeRequest GetCustomOrgUnitByCodeRequest );
		void GetCustomOrgUnitByCodeAsync( GetCustomOrgUnitByCodeRequest GetCustomOrgUnitByCodeRequest, object userState );
		void GetCustomOrgUnitByCodeAsync( GetCustomOrgUnitByCodeRequest GetCustomOrgUnitByCodeRequest );
		event GetCustomOrgUnitByCodeCompletedEventHandler GetCustomOrgUnitByCodeCompleted;
		event GetCustomOrgUnitCompletedEventHandler GetCustomOrgUnitCompleted;
		GetCustomOrgUnitTypeResponse GetCustomOrgUnitType( GetCustomOrgUnitTypeRequest GetCustomOrgUnitTypeRequest );
		void GetCustomOrgUnitTypeAsync( GetCustomOrgUnitTypeRequest GetCustomOrgUnitTypeRequest );
		void GetCustomOrgUnitTypeAsync( GetCustomOrgUnitTypeRequest GetCustomOrgUnitTypeRequest, object userState );
		event GetCustomOrgUnitTypeCompletedEventHandler GetCustomOrgUnitTypeCompleted;
		GetCustomOrgUnitTypesResponse GetCustomOrgUnitTypes( GetCustomOrgUnitTypesRequest GetCustomOrgUnitTypesRequest );
		void GetCustomOrgUnitTypesAsync( GetCustomOrgUnitTypesRequest GetCustomOrgUnitTypesRequest );
		void GetCustomOrgUnitTypesAsync( GetCustomOrgUnitTypesRequest GetCustomOrgUnitTypesRequest, object userState );
		event GetCustomOrgUnitTypesCompletedEventHandler GetCustomOrgUnitTypesCompleted;
		GetDepartmentResponse GetDepartment( GetDepartmentRequest GetDepartmentRequest );
		void GetDepartmentAsync( GetDepartmentRequest GetDepartmentRequest, object userState );
		void GetDepartmentAsync( GetDepartmentRequest GetDepartmentRequest );
		GetDepartmentResponse GetDepartmentByCode( GetDepartmentByCodeRequest GetDepartmentByCodeRequest );
		void GetDepartmentByCodeAsync( GetDepartmentByCodeRequest GetDepartmentByCodeRequest );
		void GetDepartmentByCodeAsync( GetDepartmentByCodeRequest GetDepartmentByCodeRequest, object userState );
		event GetDepartmentByCodeCompletedEventHandler GetDepartmentByCodeCompleted;
		event GetDepartmentCompletedEventHandler GetDepartmentCompleted;
		GetDepartmentOrgUnitTypeResponse GetDepartmentOrgUnitType( GetDepartmentOrgUnitTypeRequest GetDepartmentOrgUnitTypeRequest );
		void GetDepartmentOrgUnitTypeAsync( GetDepartmentOrgUnitTypeRequest GetDepartmentOrgUnitTypeRequest );
		void GetDepartmentOrgUnitTypeAsync( GetDepartmentOrgUnitTypeRequest GetDepartmentOrgUnitTypeRequest, object userState );
		event GetDepartmentOrgUnitTypeCompletedEventHandler GetDepartmentOrgUnitTypeCompleted;
		GetGroupResponse GetGroup( GetGroupRequest GetGroupRequest );
		void GetGroupAsync( GetGroupRequest GetGroupRequest, object userState );
		void GetGroupAsync( GetGroupRequest GetGroupRequest );
		GetGroupResponse GetGroupByCode( GetGroupByCodeRequest GetGroupByCodeRequest );
		void GetGroupByCodeAsync( GetGroupByCodeRequest GetGroupByCodeRequest, object userState );
		void GetGroupByCodeAsync( GetGroupByCodeRequest GetGroupByCodeRequest );
		event GetGroupByCodeCompletedEventHandler GetGroupByCodeCompleted;
		event GetGroupCompletedEventHandler GetGroupCompleted;
		GetGroupTypeResponse GetGroupType( GetGroupTypeRequest GetGroupTypeRequest );
		void GetGroupTypeAsync( GetGroupTypeRequest GetGroupTypeRequest, object userState );
		void GetGroupTypeAsync( GetGroupTypeRequest GetGroupTypeRequest );
		event GetGroupTypeCompletedEventHandler GetGroupTypeCompleted;
		GetGroupTypesResponse GetGroupTypes( GetGroupTypesRequest GetGroupTypesRequest );
		void GetGroupTypesAsync( GetGroupTypesRequest GetGroupTypesRequest, object userState );
		void GetGroupTypesAsync( GetGroupTypesRequest GetGroupTypesRequest );
		event GetGroupTypesCompletedEventHandler GetGroupTypesCompleted;
		GetOrganizationResponse GetOrganization( GetOrganizationRequest GetOrganizationRequest );
		void GetOrganizationAsync( GetOrganizationRequest GetOrganizationRequest, object userState );
		void GetOrganizationAsync( GetOrganizationRequest GetOrganizationRequest );
		event GetOrganizationCompletedEventHandler GetOrganizationCompleted;
		GetOrgUnitIdsResponse GetParentOrgUnitIds( GetParentOrgUnitIdsRequest GetParentOrgUnitIdsRequest );
		void GetParentOrgUnitIdsAsync( GetParentOrgUnitIdsRequest GetParentOrgUnitIdsRequest, object userState );
		void GetParentOrgUnitIdsAsync( GetParentOrgUnitIdsRequest GetParentOrgUnitIdsRequest );
		event GetParentOrgUnitIdsCompletedEventHandler GetParentOrgUnitIdsCompleted;
		GetSectionResponse GetSection( GetSectionRequest GetSectionRequest );
		void GetSectionAsync( GetSectionRequest GetSectionRequest );
		void GetSectionAsync( GetSectionRequest GetSectionRequest, object userState );
		GetSectionResponse GetSectionByCode( GetSectionByCodeRequest GetSectionByCodeRequest );
		void GetSectionByCodeAsync( GetSectionByCodeRequest GetSectionByCodeRequest );
		void GetSectionByCodeAsync( GetSectionByCodeRequest GetSectionByCodeRequest, object userState );
		event GetSectionByCodeCompletedEventHandler GetSectionByCodeCompleted;
		event GetSectionCompletedEventHandler GetSectionCompleted;
		GetSemesterResponse GetSemester( GetSemesterRequest GetSemesterRequest );
		void GetSemesterAsync( GetSemesterRequest GetSemesterRequest );
		void GetSemesterAsync( GetSemesterRequest GetSemesterRequest, object userState );
		GetSemesterResponse GetSemesterByCode( GetSemesterByCodeRequest GetSemesterByCodeRequest );
		void GetSemesterByCodeAsync( GetSemesterByCodeRequest GetSemesterByCodeRequest, object userState );
		void GetSemesterByCodeAsync( GetSemesterByCodeRequest GetSemesterByCodeRequest );
		event GetSemesterByCodeCompletedEventHandler GetSemesterByCodeCompleted;
		event GetSemesterCompletedEventHandler GetSemesterCompleted;
		GetSemesterOrgUnitTypeResponse GetSemesterOrgUnitType( GetSemesterOrgUnitTypeRequest GetSemesterOrgUnitTypeRequest );
		void GetSemesterOrgUnitTypeAsync( GetSemesterOrgUnitTypeRequest GetSemesterOrgUnitTypeRequest, object userState );
		void GetSemesterOrgUnitTypeAsync( GetSemesterOrgUnitTypeRequest GetSemesterOrgUnitTypeRequest );
		event GetSemesterOrgUnitTypeCompletedEventHandler GetSemesterOrgUnitTypeCompleted;
		GetSystemOrgUnitTypesResponse GetSystemOrgUnitTypes( GetSystemOrgUnitTypesRequest GetStandardOrgUnitTypesRequest );
		void GetSystemOrgUnitTypesAsync( GetSystemOrgUnitTypesRequest GetStandardOrgUnitTypesRequest, object userState );
		void GetSystemOrgUnitTypesAsync( GetSystemOrgUnitTypesRequest GetStandardOrgUnitTypesRequest );
		event GetSystemOrgUnitTypesCompletedEventHandler GetSystemOrgUnitTypesCompleted;
		RemoveChildOrgUnitResponse RemoveChildOrgUnit( RemoveChildOrgUnitRequest RemoveChildOrgUnitRequest );
		void RemoveChildOrgUnitAsync( RemoveChildOrgUnitRequest RemoveChildOrgUnitRequest );
		void RemoveChildOrgUnitAsync( RemoveChildOrgUnitRequest RemoveChildOrgUnitRequest, object userState );
		event RemoveChildOrgUnitCompletedEventHandler RemoveChildOrgUnitCompleted;
		UpdateOrgUnitResponse UpdateCourseOffering( UpdateCourseOfferingRequest UpdateCourseOfferingRequest );
		void UpdateCourseOfferingAsync( UpdateCourseOfferingRequest UpdateCourseOfferingRequest, object userState );
		void UpdateCourseOfferingAsync( UpdateCourseOfferingRequest UpdateCourseOfferingRequest );
		event UpdateCourseOfferingCompletedEventHandler UpdateCourseOfferingCompleted;
		UpdateOrgUnitResponse UpdateCourseTemplate( UpdateCourseTemplateRequest UpdateCourseTemplateRequest );
		void UpdateCourseTemplateAsync( UpdateCourseTemplateRequest UpdateCourseTemplateRequest, object userState );
		void UpdateCourseTemplateAsync( UpdateCourseTemplateRequest UpdateCourseTemplateRequest );
		event UpdateCourseTemplateCompletedEventHandler UpdateCourseTemplateCompleted;
		UpdateOrgUnitResponse UpdateCustomOrgUnit( UpdateCustomOrgUnitRequest UpdateCustomOrgUnitRequest );
		void UpdateCustomOrgUnitAsync( UpdateCustomOrgUnitRequest UpdateCustomOrgUnitRequest );
		void UpdateCustomOrgUnitAsync( UpdateCustomOrgUnitRequest UpdateCustomOrgUnitRequest, object userState );
		event UpdateCustomOrgUnitCompletedEventHandler UpdateCustomOrgUnitCompleted;
		UpdateCustomOrgUnitTypeResponse UpdateCustomOrgUnitType( UpdateCustomOrgUnitTypeRequest UpdateCustomOrgUnitTypeRequest );
		void UpdateCustomOrgUnitTypeAsync( UpdateCustomOrgUnitTypeRequest UpdateCustomOrgUnitTypeRequest, object userState );
		void UpdateCustomOrgUnitTypeAsync( UpdateCustomOrgUnitTypeRequest UpdateCustomOrgUnitTypeRequest );
		event UpdateCustomOrgUnitTypeCompletedEventHandler UpdateCustomOrgUnitTypeCompleted;
		UpdateOrgUnitResponse UpdateDepartment( UpdateDepartmentRequest UpdateDepartmentRequest );
		void UpdateDepartmentAsync( UpdateDepartmentRequest UpdateDepartmentRequest, object userState );
		void UpdateDepartmentAsync( UpdateDepartmentRequest UpdateDepartmentRequest );
		event UpdateDepartmentCompletedEventHandler UpdateDepartmentCompleted;
		UpdateOrgUnitResponse UpdateGroup( UpdateGroupRequest UpdateGroupRequest );
		void UpdateGroupAsync( UpdateGroupRequest UpdateGroupRequest );
		void UpdateGroupAsync( UpdateGroupRequest UpdateGroupRequest, object userState );
		event UpdateGroupCompletedEventHandler UpdateGroupCompleted;
		UpdateGroupTypeResponse UpdateGroupType( UpdateGroupTypeRequest UpdateGroupTypeRequest );
		void UpdateGroupTypeAsync( UpdateGroupTypeRequest UpdateGroupTypeRequest );
		void UpdateGroupTypeAsync( UpdateGroupTypeRequest UpdateGroupTypeRequest, object userState );
		event UpdateGroupTypeCompletedEventHandler UpdateGroupTypeCompleted;
		UpdateOrgUnitResponse UpdateSection( UpdateSectionRequest UpdateSectionRequest );
		void UpdateSectionAsync( UpdateSectionRequest UpdateSectionRequest );
		void UpdateSectionAsync( UpdateSectionRequest UpdateSectionRequest, object userState );
		event UpdateSectionCompletedEventHandler UpdateSectionCompleted;
		UpdateOrgUnitResponse UpdateSemester( UpdateSemesterRequest UpdateSemesterRequest );
		void UpdateSemesterAsync( UpdateSemesterRequest UpdateSemesterRequest, object userState );
		void UpdateSemesterAsync( UpdateSemesterRequest UpdateSemesterRequest );
		event UpdateSemesterCompletedEventHandler UpdateSemesterCompleted;
	}
}
